# Generated by Django 5.2.6 on 2025-10-28 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IntegrationSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jira_key', models.CharField(blank=True, max_length=255)),
                ('jira_email', models.EmailField(blank=True, max_length=254)),
                ('jira_url', models.URLField(blank=True)),
                ('google_token', models.CharField(blank=True, max_length=255)),
                ('openai_token', models.CharField(blank=True, max_length=255)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Integration Settings',
                'verbose_name_plural': 'Integration Settings',
            },
        ),
    ]
